// Code generated by mockery v2.14.0. DO NOT EDIT.

package api

import mock "github.com/stretchr/testify/mock"

// Api is an autogenerated mock type for the Api type
type Api struct {
	mock.Mock
}

// RegisterRoutes provides a mock function with given fields:
func (_m *Api) RegisterRoutes() {
	_m.Called()
}

// Run provides a mock function with given fields: port
func (_m *Api) Run(port string) error {
	ret := _m.Called(port)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(port)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewApi interface {
	mock.TestingT
	Cleanup(func())
}

// NewApi creates a new instance of Api. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApi(t mockConstructorTestingTNewApi) *Api {
	mock := &Api{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
