// Code generated by mockery v2.14.0. DO NOT EDIT.

package http

import mock "github.com/stretchr/testify/mock"

// Error is an autogenerated mock type for the Error type
type Error struct {
	mock.Mock
}

// GetStatusCodeFromError provides a mock function with given fields: err
func (_m *Error) GetStatusCodeFromError(err error) int {
	ret := _m.Called(err)

	var r0 int
	if rf, ok := ret.Get(0).(func(error) int); ok {
		r0 = rf(err)
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

type mockConstructorTestingTNewError interface {
	mock.TestingT
	Cleanup(func())
}

// NewError creates a new instance of Error. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewError(t mockConstructorTestingTNewError) *Error {
	mock := &Error{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
